In [1]:
import numpy as np

In [2]:
lst = [1,2,3]

In [3]:
type(lst)

list

In [4]:
arr = np.array(lst)

In [5]:
lst

[1, 2, 3]

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
lst[0] + lst[1]

3

In [9]:
arr[0] + arr[1]

np.int64(3)

In [10]:
lst

[1, 2, 3]

In [16]:
np.arange(stop=7,step=2)

array([0, 2, 4, 6])

In [23]:
np.zeros((5,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.full((5,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
np.random.rand(100)

array([4.40159165e-01, 1.38731083e-01, 7.66694832e-01, 1.72227360e-01,
       8.92997528e-01, 6.66378494e-01, 9.69115048e-01, 2.21617064e-01,
       8.29424916e-01, 8.75408103e-01, 5.25529995e-01, 6.03410270e-01,
       6.07235510e-01, 8.42029183e-01, 7.05659320e-01, 4.36151052e-01,
       9.94580640e-01, 1.13911631e-01, 9.09472495e-01, 3.52282546e-01,
       5.41993155e-01, 3.95864760e-01, 3.54012471e-04, 4.58239719e-01,
       5.15646864e-01, 5.50804880e-01, 5.66566483e-02, 1.72180926e-01,
       7.23569846e-01, 9.79207220e-01, 3.67110169e-01, 1.74100280e-03,
       2.49177120e-01, 1.72716924e-01, 3.57431758e-01, 5.58917565e-01,
       8.56738435e-01, 6.79172652e-02, 3.30741401e-01, 4.42167175e-01,
       9.17976562e-01, 7.48956242e-01, 9.75982163e-02, 8.33261541e-01,
       5.56197748e-01, 8.83717684e-01, 1.70312495e-01, 2.12160301e-01,
       9.77830628e-01, 6.26630384e-01, 9.44030079e-03, 8.47736277e-01,
       9.38402734e-01, 4.57533531e-01, 4.81008479e-01, 1.41772580e-01,
      

In [36]:
np.random.randn(20)

array([-2.79753884, -1.09177739,  0.3928652 , -0.59408789, -0.85672322,
        1.24769597,  0.70977489,  0.30025081, -1.38971819, -0.03247269,
       -0.80291966, -1.7312965 , -0.66452113, -0.90204442, -0.55706132,
       -0.42846281,  0.26410191,  0.16948772,  0.25740412,  1.59213467])

In [43]:
np.random.randint(1,10,(5,4))

array([[7, 2, 2, 7],
       [5, 7, 5, 4],
       [4, 6, 7, 2],
       [3, 2, 8, 5],
       [4, 2, 3, 3]], dtype=int32)

In [49]:
arr2 = np.random.randn(50)

In [52]:
arr2.max()

np.float64(2.3307510358582904)

In [53]:
arr2

array([ 4.04891888e-01, -1.47630090e+00, -2.14628759e-01, -1.56690117e+00,
       -3.27324511e-01,  2.33075104e+00,  1.04392506e+00, -1.85028237e-01,
        1.24733033e-01, -5.74687397e-01, -3.45453998e-01,  8.31698650e-01,
        9.87572033e-01,  2.70251839e-01,  9.68707919e-02,  8.29752967e-01,
        2.10432344e-01,  1.71613338e+00,  9.56561287e-01, -1.72880563e+00,
       -4.67832415e-01, -1.85341261e+00, -3.58097539e-01,  1.91484124e-01,
        1.46447694e+00, -6.15503806e-01, -3.72428473e-01,  3.54499648e-01,
        5.55855996e-01, -6.97953615e-01, -1.00059385e+00, -7.47354678e-02,
        7.88496395e-01,  6.98372408e-01,  5.93967967e-01,  5.07800667e-01,
       -8.21919666e-01,  1.80999987e-01,  4.26805767e-01,  2.81686618e-01,
       -1.91534441e+00, -6.03978899e-01, -3.62255667e-01,  2.01588173e-03,
       -7.83693511e-02,  9.61996531e-01,  1.84717585e+00, -4.04904042e-01,
        1.20656291e+00, -8.34827687e-01])

In [54]:
arr2.argmax()

np.int64(5)

In [55]:
arr2.min()

np.float64(-1.9153444092653074)

In [56]:
arr2.argmin()

np.int64(40)

In [57]:
arr3 = arr2.reshape(10,5)

In [59]:
arr3

array([[ 4.04891888e-01, -1.47630090e+00, -2.14628759e-01,
        -1.56690117e+00, -3.27324511e-01],
       [ 2.33075104e+00,  1.04392506e+00, -1.85028237e-01,
         1.24733033e-01, -5.74687397e-01],
       [-3.45453998e-01,  8.31698650e-01,  9.87572033e-01,
         2.70251839e-01,  9.68707919e-02],
       [ 8.29752967e-01,  2.10432344e-01,  1.71613338e+00,
         9.56561287e-01, -1.72880563e+00],
       [-4.67832415e-01, -1.85341261e+00, -3.58097539e-01,
         1.91484124e-01,  1.46447694e+00],
       [-6.15503806e-01, -3.72428473e-01,  3.54499648e-01,
         5.55855996e-01, -6.97953615e-01],
       [-1.00059385e+00, -7.47354678e-02,  7.88496395e-01,
         6.98372408e-01,  5.93967967e-01],
       [ 5.07800667e-01, -8.21919666e-01,  1.80999987e-01,
         4.26805767e-01,  2.81686618e-01],
       [-1.91534441e+00, -6.03978899e-01, -3.62255667e-01,
         2.01588173e-03, -7.83693511e-02],
       [ 9.61996531e-01,  1.84717585e+00, -4.04904042e-01,
         1.20656291e+00

In [60]:
arr3.min()

np.float64(-1.9153444092653074)

In [61]:
arr3.max()

np.float64(2.3307510358582904)

In [66]:
arr3.argmax(axis=1)

array([0, 0, 2, 2, 4, 3, 2, 0, 3, 1])

In [67]:
arr4 = np.random.randint(1,20,(10,5))

In [68]:
arr4

array([[ 5,  1, 10, 12,  5],
       [ 2, 12,  5, 10, 13],
       [ 5, 18,  3,  1, 11],
       [ 4, 16,  7, 19,  5],
       [ 4,  6,  1,  7, 17],
       [ 7, 15, 12,  1,  4],
       [ 6, 13, 11, 10,  5],
       [ 5, 17, 11, 18, 16],
       [18, 19,  1,  6, 11],
       [ 1, 18,  9, 13, 10]], dtype=int32)

In [70]:
arr4.argmax(axis=0)

array([8, 8, 5, 3, 4])

In [71]:
arr4.argmax()

np.int64(18)

In [78]:
row, column = np.unravel_index(arr4.argmin(), arr4.shape)

In [73]:
np.__version__

'2.4.2'

In [79]:
row,column

(np.int64(0), np.int64(1))

In [77]:
arr4.shape

(10, 5)

In [80]:
!pip list -V

Package                   Version
------------------------- -----------
anyio                     4.12.1
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.2.0
attrs                     25.4.0
babel                     2.18.0
beautifulsoup4            4.14.3
bleach                    6.3.0
certifi                   2026.1.4
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.20
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.2.0
ipython                   9.10.0
ipython_pygments_lexers   1.1.1
isoduration        


[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
