# Numpy array creation and methods

In [2]:
import numpy as np

# create a basic 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
default_zero_array = np.zeros(5) # for 1d

default_zero_array


array([0., 0., 0., 0., 0.])

In [ ]:
default_zero_array = np.zeros((3,4)) # for 2d --> remember shape need to define within parenthesis. First one represent row and second one represent column.

default_zero_array


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
default_zero_array = np.ones(5) # for 1d

default_zero_array


array([1., 1., 1., 1., 1.])

In [ ]:
default_zero_array = np.full(5, 2) # for 1d. first one for shape then the custom filler value.

default_zero_array


array([2, 2, 2, 2, 2])

In [13]:
default_zero_array = np.full((4, 3), 2) # for 1d. first one for shape then the custom filler value.

default_zero_array

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

# Creating sequence of number in numpy.

**Function Name:** `arange()`

`arange(start, stop, step)`

In [15]:
arr = np.arange(1, 10, 2)

arr

array([1, 3, 5, 7, 9])

### identity Matrix

***the the diagonal will be 1 and rest value are 0 and this is a square matrix***

`eye(size)`

In [17]:
# identity matrix

identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])